/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment spec 'org.genivi.commonapi.dbus.deployment'
*******************************************************************************/
package org.genivi.commonapi.dbus;

import org.franca.core.franca.FInterface;
import org.franca.core.franca.FAttribute;
import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'org.genivi.commonapi.dbus.deployment' specification
 */		
public class DeploymentInterfacePropertyAccessor
	extends org.genivi.commonapi.core.DeploymentInterfacePropertyAccessor
{
	
	private FDeployedInterface target;

	public DeploymentInterfacePropertyAccessor (FDeployedInterface target) {
		super(target);
		this.target = target;
	}
	
	public enum DBusDefaultAttributeType {
		CommonAPI, freedesktop
	}
	public DBusDefaultAttributeType getDBusDefaultAttributeType (FInterface obj) {
		String e = target.getEnum(obj, "DBusDefaultAttributeType");
		if (e==null) return null;
		return convertDBusDefaultAttributeType(e);
	}
	private DBusDefaultAttributeType convertDBusDefaultAttributeType (String val) {
		if (val.equals("CommonAPI"))
			return DBusDefaultAttributeType.CommonAPI; else 
		if (val.equals("freedesktop"))
			return DBusDefaultAttributeType.freedesktop;
		return null;
	}
	
	public enum DBusAttributeType {
		CommonAPI, freedesktop
	}
	public DBusAttributeType getDBusAttributeType (FAttribute obj) {
		String e = target.getEnum(obj, "DBusAttributeType");
		if (e==null) return null;
		return convertDBusAttributeType(e);
	}
	private DBusAttributeType convertDBusAttributeType (String val) {
		if (val.equals("CommonAPI"))
			return DBusAttributeType.CommonAPI; else 
		if (val.equals("freedesktop"))
			return DBusAttributeType.freedesktop;
		return null;
	}
	
	
}
