/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment spec 'org.genivi.commonapi.dbus.deployment'
*******************************************************************************/
package org.genivi.commonapi.dbus;

import org.franca.core.franca.FInterface;
import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'org.genivi.commonapi.dbus.deployment' specification
 */		
public class DeploymentTypeCollectionPropertyAccessor
	extends org.genivi.commonapi.core.DeploymentTypeCollectionPropertyAccessor
{
	
	private FDeployedTypeCollection target;

	public DeploymentTypeCollectionPropertyAccessor (FDeployedTypeCollection target) {
		super(target);
		this.target = target;
	}
	
	public enum DBusDefaultAttributeType {
		CommonAPI, freedesktop
	}
	public DBusDefaultAttributeType getDBusDefaultAttributeType (FInterface obj) {
		String e = target.getEnum(obj, "DBusDefaultAttributeType");
		if (e==null) return null;
		return convertDBusDefaultAttributeType(e);
	}
	private DBusDefaultAttributeType convertDBusDefaultAttributeType (String val) {
		if (val.equals("CommonAPI"))
			return DBusDefaultAttributeType.CommonAPI; else 
		if (val.equals("freedesktop"))
			return DBusDefaultAttributeType.freedesktop;
		return null;
	}
	
	
}
