/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment spec 'org.genivi.commonapi.dbus.deployment'
*******************************************************************************/
package org.genivi.commonapi.dbus;

import org.franca.core.franca.FInterface;
import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'org.genivi.commonapi.dbus.deployment' specification
 */		
public class DeploymentInterfacePropertyAccessor
	extends org.genivi.commonapi.core.DeploymentInterfacePropertyAccessor
{
	
	private FDeployedInterface target;

	public DeploymentInterfacePropertyAccessor (FDeployedInterface target) {
		super(target);
		this.target = target;
	}
	
	public enum PropertiesType {
		CommonAPI, freedesktop
	}
	public PropertiesType getPropertiesType (FInterface obj) {
		String e = target.getEnum(obj, "PropertiesType");
		if (e==null) return null;
		return convertPropertiesType(e);
	}
	private PropertiesType convertPropertiesType (String val) {
		if (val.equals("CommonAPI"))
			return PropertiesType.CommonAPI; else 
		if (val.equals("freedesktop"))
			return PropertiesType.freedesktop;
		return null;
	}
	
	
}
