/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment spec 'org.genivi.commonapi.dbus.deployment'
*******************************************************************************/
package org.genivi.commonapi.dbus;

import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'org.genivi.commonapi.dbus.deployment' specification
 */		
public class DeploymentProviderPropertyAccessor
	extends org.genivi.commonapi.core.DeploymentProviderPropertyAccessor
{
	
	private FDeployedProvider target;

	public DeploymentProviderPropertyAccessor (FDeployedProvider target) {
		super(target);
		this.target = target;
	}
	
	
}
