/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment spec 'org.genivi.commonapi.dbus.deployment'
*******************************************************************************/
package org.genivi.commonapi.dbus;

import org.franca.deploymodel.dsl.fDeploy.FDInterfaceInstance;
import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'org.genivi.commonapi.dbus.deployment' specification
 */		
public class DeploymentProviderPropertyAccessor
	extends org.genivi.commonapi.core.DeploymentProviderPropertyAccessor
{
	
	private FDeployedProvider target;

	public DeploymentProviderPropertyAccessor (FDeployedProvider target) {
		super(target);
		this.target = target;
	}
	
	public String getDBusServiceName (FDInterfaceInstance obj) {
		return target.getString(obj, "DBusServiceName");
	}
	
	public String getDBusObjectPath (FDInterfaceInstance obj) {
		return target.getString(obj, "DBusObjectPath");
	}
	
	public String getDBusInterfaceName (FDInterfaceInstance obj) {
		return target.getString(obj, "DBusInterfaceName");
	}
	
	public enum DBusBusType {
		system, session
	}
	public DBusBusType getDBusBusType (FDInterfaceInstance obj) {
		String e = target.getEnum(obj, "DBusBusType");
		if (e==null) return null;
		return convertDBusBusType(e);
	}
	private DBusBusType convertDBusBusType (String val) {
		if (val.equals("system"))
			return DBusBusType.system; else 
		if (val.equals("session"))
			return DBusBusType.session;
		return null;
	}
	
	public Boolean getDBusPredefined (FDInterfaceInstance obj) {
		return target.getBoolean(obj, "DBusPredefined");
	}
	
	
}
