name: CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: "Checkout capicxx-core-tools"
      uses: actions/checkout@v3 
      with:
        repository: COVESA/capicxx-core-tools
        path: capicxx-core-tools

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: install dbus
      run: |
          sudo apt-get update -qq
          sudo apt-get install -y dbus libdbus-1-dev

    - name: Build capicxx-core-tools
      run: mvn -f org.genivi.commonapi.core.releng/pom.xml -D target.id=org.genivi.commonapi.core.target clean verify
      working-directory: capicxx-core-tools
      
    - name: Build apicxx-dbus-tools
      run: mvn -D COREPATH=capicxx-core-tools -f org.genivi.commonapi.dbus.releng/pom.xml -D target.id=org.genivi.commonapi.dbus.target clean verify
